name: we_the_heroes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.7+3
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  firebase_database: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_white.png
    - assets/images/google.png
  fonts:
    - family: Scriptina
      fonts:
        - asset: assets/fonts/Scriptina-Regular.ttf